spring:
  profiles:
    active: local

mybatis:
  mapper-locations: mappers/*.xml
  type-aliases-package: com.him.fpjt.him_backend.exercise.domain, com.him.fpjt.him_backend.user.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/ssafydb?serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234

