name: Java CI with Gradle

on:
  push:
    branches: [ "main", "infra/**" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    permissions:
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      env:
        SPRING_PROFILES_ACTIVE: local
        MAIL_HOST: ${{ secrets.MAIL_HOST }}
        MAIL_USERNAME: ${{ secrets.MAIL_USERNAME }}
        MAIL_PASSWORD: ${{ secrets.MAIL_PASSWORD }}
        SECRET_KEY: ${{ secrets.SECRET_KEY }}
        JWT_EXPIRATION: ${{ secrets.JWT_EXPIRATION }}
        REFRESH_EXPIRATION: ${{ secrets.REFRESH_EXPIRATION }}
      run: ./gradlew clean build -i

   
    - name: Make Directory for deliver
      run: mkdir deploy

    - name: Copy Jar
      run: cp ./build/libs/*.jar ./deploy/

    - name: Make zip file
      run: zip -r -qq -j ./springboot-intro-build.zip ./deploy

    - name: Deliver to AWS S3
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}
      run: |
        aws s3 cp \
        --region ap-northeast-2 \
        --acl private \ ./springboot-intro-build.zip s3://springboot-intro-build/
